# Backend Dockerfile
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install && npm install -g nodemon

# Copy the source code
COPY . .

# Expose the backend port
EXPOSE 3001

# Start the backend
CMD ["nodemon", "src/server.js"]
